document.addEventListener('DOMContentLoaded', function() {
    const courseForm = document.getElementById('courseForm');
    const courseId = document.getElementById('courseId');
    const createdAt = document.getElementById('createdAt');
    const updatedAt = document.getElementById('updatedAt');

    // Function to show Home page
    window.showHome = function() {
        hideAllContents();
        document.getElementById('home-content').style.display = 'block';
        document.getElementById('lab-menu').style.display = 'none'; // Hide mini menu
    };

    // Function to show About page
    window.showAbout = function() {
        hideAllContents();
        document.getElementById('about-content').style.display = 'block';
        document.getElementById('lab-menu').style.display = 'none'; // Hide mini menu
    };

    // Function to show Lab 1 content
    window.showLab1 = function() {
        hideLabContents();
        document.getElementById('lab1-content').style.display = 'block';
    };

    // Function to show Lab 2 content
    window.showLab2 = function() {
        hideLabContents();
        document.getElementById('lab2-content').style.display = 'block';
    };

    // Hide all main contents
    function hideAllContents() {
        document.getElementById('home-content').style.display = 'none';
        document.getElementById('about-content').style.display = 'none';
        document.getElementById('labs-content').style.display = 'none';
        hideLabContents();
    }

    // Hide all lab-specific content
    function hideLabContents() {
        document.getElementById('lab1-content').style.display = 'none';
        document.getElementById('lab2-content').style.display = 'none';
    }

    // Simulating dynamic ID and timestamp generation for demonstration
    function generateCourseId() {
        return 'COURSE-' + Math.floor(Math.random() * 10000);
    }

    function getCurrentTimestamp() {
        const now = new Date();
        return now.toISOString().slice(0, 19).replace('T', ' ');
    }

    // Populate auto-generated fields when the form is loaded
    function populateAutoGeneratedFields() {
        if (!courseId.value) {
            courseId.value = generateCourseId();  // Generate and display course ID
        }
        if (!createdAt.value) {
            createdAt.value = getCurrentTimestamp();  // Set creation timestamp
        }
        updatedAt.value = getCurrentTimestamp();  // Set the last updated timestamp
    }

    // Form submission handler
    courseForm.addEventListener('submit', function(event) {
        event.preventDefault();

        // Basic validation (course name required)
        const courseName = document.getElementById('courseName').value;
        if (!courseName) {
            alert('Course name is required');
            return;
        }

        // Update the "Last Updated" timestamp
        updatedAt.value = getCurrentTimestamp();

        alert('Course Created/Updated Successfully!');
    });

    // Pre-populate the form with auto-generated fields on load
    populateAutoGeneratedFields();
});

    // Toggling Group Content
    function toggleGroup(groupId) {
        var group = document.getElementById(groupId);
          if (group.style.display === "none" || group.style.display === "") {
              group.style.display = "block";
          } else {
              group.style.display = "none";
          }
    }